config/routes.rb
Rails.application.routes.draw do

  root 'lovers#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  resources :lovers do
    get :invite
    post :partner
    get :join_partners
    get :seperate_partners
  end

  resources :memories

end

app/models/lover.rb
class Lover < ActiveRecord::Base
  has_many :memories
  has_one :lover

   def self.register_from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) if auth.credentials.expires
      user.save!
    end
  end

  def partner
    self.lover || NullLover.new
  end

  def partner=(lover)
    self.lover = lover
  end
end

class NullLover
  def method_missing *args
    nil
  end
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  belongs_to :lover
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= Lover.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    if session[:user_id].nil?
      session[:request_url] = request.url if request.get?
      redirect_to '/auth/google_oauth2'
    end
  end

  helper_method :current_user
end

app/controllers/lovers_controller.rb
class LoversController < ApplicationController
  before_action :set_lover, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate!

  # GET /lovers
  # GET /lovers.json
  def index
    @lover = current_user
  end

  # GET /lovers/1
  # GET /lovers/1.json
  def show
  end

  # GET /lovers/new
  def new
    @lover = Lover.new
  end

  # GET /lovers/1/edit
  def edit
  end

  def invite
  end

  def join_partners
    lover = Lover.find params['lover_id']
    invitee = current_user
    if lover.partner.name.nil? && invitee.partner.name.nil?
      lover.partner, invitee.partner = invitee, lover
      lover.save
      invitee.save
      redirect_to lovers_path
    else
      render 'partner_failed'
    end
  end

  def seperate_partners
    lover = Lover.find params['lover_id']
    invitee = current_user
    if lover.partner == invitee && invitee.partner == lover
      lover.partner, invitee.partner = nil, nil
      lover.save
      invitee.save
      redirect_to lovers_path
    else
      render 'partner_failed'
    end
  end

  def partner
    InviteMailer.lover_email(params['lover_id'], params['invitee']).deliver
  end

  # POST /lovers
  # POST /lovers.json
  def create
    @lover = Lover.new(lover_params)

    respond_to do |format|
      if @lover.save
        format.html { redirect_to @lover, notice: 'Lover was successfully created.' }
        format.json { render :show, status: :created, location: @lover }
      else
        format.html { render :new }
        format.json { render json: @lover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lovers/1
  # PATCH/PUT /lovers/1.json
  def update
    respond_to do |format|
      if @lover.update(lover_params)
        format.html { redirect_to @lover, notice: 'Lover was successfully updated.' }
        format.json { render :show, status: :ok, location: @lover }
      else
        format.html { render :edit }
        format.json { render json: @lover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lovers/1
  # DELETE /lovers/1.json
  def destroy
    @lover.destroy
    respond_to do |format|
      format.html { redirect_to lovers_url, notice: 'Lover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lover
      @lover = Lover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lover_params
      params.require(:lover).permit(:name, :secret_answer, :secret_question)
    end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(memory_params)

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: 'Memory was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: 'Memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to memories_url, notice: 'Memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_params
      params.require(:memory).permit(:title, :description, :private, :about_id)
    end
end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  def create
    user = Lover.check_from_omniauth(env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Signed In"
      redirect_to :back
    else
      flash[:notice] = "Not Authorized"
      redirect_to root_url
    end
  rescue ActionController::RedirectBackError
    store_location = session[:request_url]
    redirect_to( store_location || root_url )
  end

  def destroy
    session.delete :user_id
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = Lover.register_from_omniauth(env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Signed In"
      redirect_to :back
    else
      flash[:notice] = "Not Authorized"
      redirect_to root_url
    end
  rescue ActionController::RedirectBackError
    store_location = session[:request_url]
    redirect_to( store_location || root_url )
  end

  def destroy
    session.delete :user_id
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lovers_helper.rb
module LoversHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ILoveSavannah</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lovers/_form.html.erb
<%= form_for(@lover) do |f| %>
  <% if @lover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lover.errors.count, "error") %> prohibited this lover from being saved:</h2>

      <ul>
      <% @lover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :secret_answer %><br>
    <%= f.text_field :secret_answer %>
  </div>
  <div class="field">
    <%= f.label :secret_question %><br>
    <%= f.text_field :secret_question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lovers/edit.html.erb
<h1>Editing lover</h1>

<%= render 'form' %>

<%= link_to 'Show', @lover %> |
<%= link_to 'Back', lovers_path %>

app/views/lovers/index.html.erb
<h1>Listing lovers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Secret answer</th>
      <th>Secret question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @lover.name %></td>
      <td><%= @lover.secret_answer %></td>
      <td><%= @lover.secret_question %></td>
      <td><%= link_to 'Show', @lover %></td>
      <td><%= link_to 'Edit', edit_lover_path(@lover) %></td>
    </tr>
    <% if @lover.partner.name.nil? %>
      <tr>
        <td>No Partner</td>
        <td></td>
        <td></td>
        <td><%= link_to 'Invite', lover_invite_path(@lover) %></td>
      </tr>
    <% else %>
      <tr>
        <td><%= @lover.partner.name %></td>
        <td><%= @lover.partner.secret_answer %></td>
        <td><%= @lover.partner.secret_question %></td>
        <td><%= link_to 'Show', lover_path(@lover.partner) %></td>
        <td><%= link_to 'Seperate', lover_seperate_partners_path(@lover.partner) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lovers/invite.html.erb
<%= form_tag(lover_partner_path(current_user), method: "post") do %>
  <%= label_tag(:invitee, "Email:") %>
  <%= text_field_tag(:invitee) %>
  <%= submit_tag("Invite") %>
<% end %>

app/views/lovers/new.html.erb
<h1>New lover</h1>

<%= render 'form' %>

<%= link_to 'Back', lovers_path %>

app/views/lovers/partner.html.erb
<h1>Email Sent Cross your fingers</h1>

app/views/lovers/partner_failed.html.erb
<h1>Failed</h1>

app/views/lovers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lover.name %>
</p>

<p>
  <strong>Secret answer:</strong>
  <%= @lover.secret_answer %>
</p>

<p>
  <strong>Secret question:</strong>
  <%= @lover.secret_question %>
</p>

<%= link_to 'Edit', edit_lover_path(@lover) %> |
<%= link_to 'Back', lovers_path %>

app/views/memories/_form.html.erb
<%= form_for(@memory) do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% @memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :about_id %><br>
    <%= f.text_field :about_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memories/edit.html.erb
<h1>Editing memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

app/views/memories/index.html.erb
<h1>Listing memories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Private</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memories.each do |memory| %>
      <tr>
        <td><%= memory.title %></td>
        <td><%= memory.description %></td>
        <td><%= memory.private %></td>
        <td><%= memory.about %></td>
        <td><%= link_to 'Show', memory %></td>
        <td><%= link_to 'Edit', edit_memory_path(memory) %></td>
        <td><%= link_to 'Destroy', memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory', new_memory_path %>

app/views/memories/new.html.erb
<h1>New memory</h1>

<%= render 'form' %>

<%= link_to 'Back', memories_path %>

app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @memory.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @memory.description %>
</p>

<p>
  <strong>Private:</strong>
  <%= @memory.private %>
</p>

<p>
  <strong>About:</strong>
  <%= @memory.about %>
</p>

<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>